<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JHURRHK" failures="4" tests="13" name="studi.co.testScripts.AFS_UserStory_63" time="1004.028" errors="0" timestamp="15 Aug 2021 08:01:19 GMT" skipped="0">
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC01_Verify_Create_Note_Icon_Should_Be_Visible_In_Video" time="59.771"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC02_Verify_Create_Note_Icon_Should_Be_Clickable_In_Video" time="76.823"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC08_Verify_Save_Note_Button_Should_Be_Disable_Initially" time="71.411">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_Button_Should_Be_Disable_Initially(Module_Syllabus_Options.java:2042)
at studi.co.testScripts.AFS_UserStory_63.TC08_Verify_Save_Note_Button_Should_Be_Disable_Initially(AFS_UserStory_63.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC08_Verify_Save_Note_Button_Should_Be_Disable_Initially -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC43_Verify_Notes_Will_Be_Saved_Using_Save_Note_Option" time="89.572"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC11_Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note" time="78.133">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true],
	Discard Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true],
Discard Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note(Module_Syllabus_Options.java:2303)
at studi.co.testScripts.AFS_UserStory_63.TC11_Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note(AFS_UserStory_63.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC11_Verify_Save_Note_And_Discard_Button_Enable_After_User_Entering_Note -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC06_Verify_User_Is_Unable_To_Add_Empty_Note" time="80.228"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC10_Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially" time="81.737">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true],
	Discard Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true],
Discard Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially(Module_Syllabus_Options.java:2192)
at studi.co.testScripts.AFS_UserStory_63.TC10_Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially(AFS_UserStory_63.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC10_Verify_Save_Note_And_Discard_Button_Should_Be_Disable_Initially -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC14_Verify_Note_Module_Will_Closed_Without_Warning" time="77.823"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC15_Verify_Note_Area_Have_Initial_Message_For_Entering_Text" time="74.184"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC42_Verify_Warning_Message_Shown_After_Clicking_Discard_In_Notes" time="90.075"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC05_Verify_User_Should_Be_Able_To_Write_Upto_3000_Charcters_In_Note" time="76.144"/>
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC09_Verify_Save_Note_Button_Enable_After_User_Entering_Note" time="73.366">
    <failure message="The following asserts failed:
	Save note Button clickable without entering Text expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Save note Button clickable without entering Text expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at studi.co.pageModules.Module_Syllabus_Options.Verify_Save_Note_Button_Enable_After_User_Entering_Note(Module_Syllabus_Options.java:2117)
at studi.co.testScripts.AFS_UserStory_63.TC09_Verify_Save_Note_Button_Enable_After_User_Entering_Note(AFS_UserStory_63.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC09_Verify_Save_Note_Button_Enable_After_User_Entering_Note -->
  <testcase classname="studi.co.testScripts.AFS_UserStory_63" name="TC07_Verify_User_Is_Able_To_Enter_Special_Characters_In_Note" time="74.761"/>
</testsuite> <!-- studi.co.testScripts.AFS_UserStory_63 -->
